# This is a basic workflow to help you get started with Actions

name: Blob storage website CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.MY_AZURE_CREDS }}
          
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: v2.33.1
        inlineScript: |
            az storage blob upload-batch --account-name bennyresumestorage --auth-mode key -d '$web' -s . --connection-string 'DefaultEndpointsProtocol=https;AccountName=bennyresumestorage;AccountKey=+SrJXjr2eIBBkMIix8Wo75YuM7i7gycMLbwL0wIJ3LBFfTcyMQKcW56ADeDzwfWXKrJjlLDUhcv5PmE7OHdPOw==;EndpointSuffix=core.windows.net'
            
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "resume" --name "benny-resume" --resource-group "ResumeChallenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
